DROP TABLE IF EXISTS employee;
	 
CREATE TABLE employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  EMPLOYEE_ID VARCHAR(15) NOT NULL,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL_ID  VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(25) NOT NULL,
  DESIGNATION VARCHAR(250) DEFAULT NULL,
  DATE_OF_BIRTH TIMESTAMP NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  MARITAL_STATUS VARCHAR(10) NOT NULL,
  BLOOD_GROUP VARCHAR(5) NOT NULL,
  ADDRESS VARCHAR(1000) NOT NULL
);
	
INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0001', 'James','David', 'James.David@cognizant.com',  '(257) 563-7401', 'Sr.Developer',PARSEDATETIME('02/03/1990', 'dd/MM/yyyy'), 'Male', 'Married', 'A+', '711-2880 Nulla St.Mankato Mississippi 96522.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0002', 'Amy','Thomas', 'Richard.Thomas@cognizant.com',  '(372) 587-2335', 'Developer',PARSEDATETIME('26/05/1995', 'dd/MM/yyyy'), 'Female', 'Single', 'B+', '#P.O. Box 283 8562 Fusce Rd.Frederick Nebraska 20620.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0003', 'Hellen','William', 'Micheal.William@cognizant.com',  '(786) 713-8616', 'Developer',PARSEDATETIME('09/12/1994', 'dd/MM/yyyy'), 'Female', 'Single', 'AB+', '606-3727 Ullamcorper. Street Roseville NH 11523.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0004', 'Charles','Paul', 'Charles.Paul@cognizant.com',  '(793) 151-6230', 'Manager',PARSEDATETIME('01/01/1989', 'dd/MM/yyyy'), 'Male', 'Married', 'O+', 'Ap #867-859 Sit Rd.Azusa New York 39531.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0005', 'Daniel','Mark', 'Daniel.Mark@cognizant.com',  '(492) 709-6392', 'Sr.Manager',PARSEDATETIME('30/07/1995', 'dd/MM/yyyy'), 'Male', 'Single', 'O-', '7292 Dictum Av.
San Antonio MI 47096.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0006', 'Nancy','Brian', 'Nancy.Brian@cognizant.com',  '(654) 393-5734', 'Tester',PARSEDATETIME('12/12/1990', 'dd/MM/yyyy'), 'Female', 'Single', 'AB+', 'Ap #651-8679 Sodales Av.Tamuning PA 10855.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0007', 'Jason','Mathew', 'Jason.Mathew@cognizant.com',  '(404) 960-3807', 'Sr.Developer',PARSEDATETIME('02/02/1992', 'dd/MM/yyyy'), 'Male', 'Married', 'A+', '191-103 Integer Rd.
Corona New Mexico 08219.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0008', 'Stephen','Eric', 'Stephen.Eric@cognizant.com',  '(314) 244-6306', 'Programmer',PARSEDATETIME('02/03/1993', 'dd/MM/yyyy'), 'Male', 'Single', 'AB-', 'P.O. Box 887 2508 Dolor. Av.Muskegon KY 12482.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0009', 'Mary','Mark', 'Mary.Mark@cognizant.com',  '(947) 278-5929', 'Architect',PARSEDATETIME('10/08/1995', 'dd/MM/yyyy'), 'Female', 'Married', 'B-', 'P.O. Box 132 1599 Curabitur Rd.Bandera South Dakota 45149.');

INSERT INTO EMPLOYEE( EMPLOYEE_ID, FIRST_NAME ,LAST_NAME, EMAIL_ID, PHONE_NUMBER, DESIGNATION, DATE_OF_BIRTH, GENDER, MARITAL_STATUS, BLOOD_GROUP, ADDRESS ) 
VALUES('AZ0010', 'Donald','Brian', 'Donald.Brian@cognizant.com',  '(684) 579-1879', 'Sr.Manager',PARSEDATETIME('16/11/1985', 'dd/MM/yyyy'), 'Male', 'Married', 'B+', '347-7666 Iaculis St.Woodruff SC 49854.');